# Generated by Django 4.2.26 on 2026-06-10 12:02

import accounts.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('departments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('designations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updated_at')),
                ('deleted_at', models.DateTimeField(blank=True, db_column='deleted_at', null=True)),
                ('is_active', models.BooleanField(db_column='is_active', default=True)),
                ('th_urid', models.CharField(db_column='th_urid', default=accounts.models.generate_custom_th_urid, editable=False, max_length=36, unique=True)),
                ('date_of_joining', models.DateField(db_column='date_of_joining')),
                ('date_of_birth', models.DateField(blank=True, db_column='date_of_birth', null=True)),
                ('date_of_leaving', models.DateField(blank=True, db_column='date_of_leaving', help_text='Populated on separation / resignation', null=True)),
                ('gender', models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other / Prefer not to say')], db_column='gender', max_length=1, null=True)),
                ('monthly_honorarium', models.DecimalField(db_column='monthly_honorarium', decimal_places=2, help_text='Gross base pay (Monthly Honorarium) in INR — the figure before any deductions', max_digits=12)),
                ('bank_name', models.CharField(blank=True, db_column='bank_name', max_length=200, null=True)),
                ('bank_account_number', models.CharField(blank=True, db_column='bank_account_number', max_length=50, null=True)),
                ('bank_ifsc', models.CharField(blank=True, db_column='bank_ifsc', max_length=20, null=True)),
                ('bank_branch', models.CharField(blank=True, db_column='bank_branch', max_length=200, null=True)),
                ('pan_number', models.CharField(blank=True, db_column='pan_number', help_text='Permanent Account Number — mandatory for TDS deductions', max_length=20, null=True)),
                ('uan_number', models.CharField(blank=True, db_column='uan_number', help_text='Universal Account Number — mandatory for EPF deductions', max_length=20, null=True)),
                ('esic_ip_number', models.CharField(blank=True, db_column='esic_ip_number', help_text='ESIC Insurance Policy (IP) Number', max_length=20, null=True)),
                ('aadhaar_number', models.CharField(blank=True, db_column='aadhaar_number', max_length=20, null=True)),
                ('address', models.TextField(blank=True, db_column='address', null=True)),
                ('city', models.CharField(blank=True, db_column='city', max_length=100, null=True)),
                ('state', models.CharField(blank=True, db_column='state', max_length=100, null=True)),
                ('pincode', models.CharField(blank=True, db_column='pincode', max_length=10, null=True)),
                ('emergency_contact_name', models.CharField(blank=True, db_column='emergency_contact_name', max_length=200, null=True)),
                ('emergency_contact_phone', models.CharField(blank=True, db_column='emergency_contact_phone', max_length=15, null=True)),
                ('emergency_contact_relation', models.CharField(blank=True, db_column='emergency_contact_relation', max_length=100, null=True)),
                ('created_by', models.ForeignKey(blank=True, db_column='created_by', db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, db_column='deleted_by', db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(db_column='department_id', on_delete=django.db.models.deletion.PROTECT, related_name='employees', to='departments.department')),
                ('designation', models.ForeignKey(db_column='designation_id', on_delete=django.db.models.deletion.PROTECT, related_name='employees', to='designations.designation')),
                ('updated_by', models.ForeignKey(blank=True, db_column='updated_by', db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='employee_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'emp_profiles',
                'ordering': ['user__employee_code'],
            },
        ),
    ]
