# Generated by Django 4.2.26 on 2026-06-20 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeprofile',
            name='job_seeker_id',
            field=models.CharField(blank=True, db_column='job_seeker_id', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='theme',
            field=models.TextField(blank=True, db_column='theme', null=True),
        ),
    ]
