# Generated by Django 4.2.26 on 2026-06-30 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0003_tdsform'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeprofile',
            name='caste_category',
            field=models.CharField(blank=True, db_column='caste_category', max_length=1, null=True),
        ),
    ]
