# Generated by Django 4.2.26 on 2026-06-30 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0004_employeeprofile_caste_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeprofile',
            name='caste_category',
            field=models.CharField(blank=True, db_column='caste_category', max_length=255, null=True),
        ),
    ]
