# Generated by Django 4.2.26 on 2026-06-10 12:02

import accounts.models
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('departments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalaryStructure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updated_at')),
                ('deleted_at', models.DateTimeField(blank=True, db_column='deleted_at', null=True)),
                ('is_active', models.BooleanField(db_column='is_active', default=True)),
                ('th_urid', models.CharField(db_column='th_urid', default=accounts.models.generate_custom_th_urid, editable=False, max_length=36, unique=True)),
                ('tds_rate', models.DecimalField(db_column='tds_rate', decimal_places=2, default=10.0, help_text='TDS percentage, e.g. 10.00 for 10 %', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('epf_rate', models.DecimalField(db_column='epf_rate', decimal_places=2, default=12.0, help_text='EPF percentage, e.g. 12.00 for 12 %', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('esic_rate', models.DecimalField(db_column='esic_rate', decimal_places=2, default=3.85, help_text='ESIC percentage, e.g. 3.85 for 3.85 %', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('effective_from', models.DateField(db_column='effective_from', help_text='First date on which these rates apply')),
                ('effective_to', models.DateField(blank=True, db_column='effective_to', help_text='Leave blank if this is the current active structure', null=True)),
                ('remarks', models.TextField(blank=True, db_column='remarks', null=True)),
                ('created_by', models.ForeignKey(blank=True, db_column='created_by', db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, db_column='deleted_by', db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(db_column='department_id', on_delete=django.db.models.deletion.PROTECT, related_name='salary_structures', to='departments.department')),
                ('updated_by', models.ForeignKey(blank=True, db_column='updated_by', db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'core_salary_structures',
                'ordering': ['department', '-effective_from'],
            },
        ),
    ]
