# Generated by Django 4.2.26 on 2026-07-14 06:15

import accounts.models
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('employees', '0005_alter_employeeprofile_caste_category'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomSalaryStructure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updated_at')),
                ('deleted_at', models.DateTimeField(blank=True, db_column='deleted_at', null=True)),
                ('is_active', models.BooleanField(db_column='is_active', default=True)),
                ('th_urid', models.CharField(db_column='th_urid', default=accounts.models.generate_custom_th_urid, editable=False, max_length=36, unique=True)),
                ('tds_amount', models.DecimalField(db_column='tds_amount', decimal_places=2, default=0.0, help_text='Fixed TDS deduction amount in INR.', max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('epf_amount', models.DecimalField(db_column='epf_amount', decimal_places=2, default=0.0, help_text='Fixed EPF deduction amount in INR.', max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('esic_amount', models.DecimalField(db_column='esic_amount', decimal_places=2, default=0.0, help_text='Fixed ESIC deduction amount in INR.', max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('effective_from', models.DateField(db_column='effective_from', help_text='First date on which these custom fixed amounts apply.')),
                ('effective_to', models.DateField(blank=True, db_column='effective_to', help_text='Leave blank if this is the currently active custom structure.', null=True)),
                ('remarks', models.TextField(blank=True, db_column='remarks', help_text='Reason for applying a custom fixed deduction.', null=True)),
                ('created_by', models.ForeignKey(blank=True, db_column='created_by', db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, db_column='deleted_by', db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(db_column='employee_id', help_text='The specific employee this custom structure applies to.', on_delete=django.db.models.deletion.CASCADE, related_name='custom_salary_structures', to='employees.employeeprofile')),
                ('updated_by', models.ForeignKey(blank=True, db_column='updated_by', db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'core_custom_salary_structures',
                'ordering': ['employee', '-effective_from'],
            },
        ),
    ]
