# Generated by Django 4.2.26 on 2026-06-08 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='role',
            table='acc_roles',
        ),
        migrations.AlterModelTable(
            name='user',
            table='acc_users',
        ),
    ]
