# Generated by Django 4.2.26 on 2026-06-10 12:02

import accounts.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('departments', '0001_initial'),
        ('employees', '0001_initial'),
        ('attendance', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('designations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PayrollRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updated_at')),
                ('deleted_at', models.DateTimeField(blank=True, db_column='deleted_at', null=True)),
                ('is_active', models.BooleanField(db_column='is_active', default=True)),
                ('th_urid', models.CharField(db_column='th_urid', default=accounts.models.generate_custom_th_urid, editable=False, max_length=36, unique=True)),
                ('pay_month', models.PositiveSmallIntegerField(db_column='pay_month', help_text='Calendar month (1 – 12)')),
                ('pay_year', models.PositiveIntegerField(db_column='pay_year')),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('APPROVED', 'Approved'), ('LOCKED', 'Locked')], db_column='status', default='DRAFT', max_length=20)),
                ('total_gross', models.DecimalField(db_column='total_gross', decimal_places=2, default=0, max_digits=14)),
                ('total_deductions', models.DecimalField(db_column='total_deductions', decimal_places=2, default=0, max_digits=14)),
                ('total_net', models.DecimalField(db_column='total_net', decimal_places=2, default=0, max_digits=14)),
                ('processed_at', models.DateTimeField(blank=True, db_column='processed_at', null=True)),
                ('approved_at', models.DateTimeField(blank=True, db_column='approved_at', null=True)),
                ('remarks', models.TextField(blank=True, db_column='remarks', null=True)),
                ('approved_by', models.ForeignKey(blank=True, db_column='approved_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_payroll_runs', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, db_column='created_by', db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, db_column='deleted_by', db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(db_column='department_id', on_delete=django.db.models.deletion.PROTECT, related_name='payroll_runs', to='departments.department')),
                ('salary_structure', models.ForeignKey(db_column='salary_structure_id', help_text='Deduction-rate snapshot used for this run', on_delete=django.db.models.deletion.PROTECT, related_name='payroll_runs', to='core.salarystructure')),
                ('updated_by', models.ForeignKey(blank=True, db_column='updated_by', db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'pay_payroll_runs',
                'ordering': ['-pay_year', '-pay_month', 'department'],
                'unique_together': {('department', 'pay_month', 'pay_year')},
            },
        ),
        migrations.CreateModel(
            name='DesignationPayrollRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updated_at')),
                ('deleted_at', models.DateTimeField(blank=True, db_column='deleted_at', null=True)),
                ('is_active', models.BooleanField(db_column='is_active', default=True)),
                ('th_urid', models.CharField(db_column='th_urid', default=accounts.models.generate_custom_th_urid, editable=False, max_length=36, unique=True)),
                ('applies_tds', models.BooleanField(db_column='applies_tds', default=False, help_text='Deduct TDS (10 %) from Monthly Honorarium')),
                ('applies_epf', models.BooleanField(db_column='applies_epf', default=False, help_text='Deduct EPF (12 %) from Monthly Honorarium')),
                ('applies_esic', models.BooleanField(db_column='applies_esic', default=False, help_text='Deduct ESIC (3.85 %) — only valid when applies_epf is also True')),
                ('remarks', models.TextField(blank=True, db_column='remarks', null=True)),
                ('created_by', models.ForeignKey(blank=True, db_column='created_by', db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, db_column='deleted_by', db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('designation', models.OneToOneField(db_column='designation_id', on_delete=django.db.models.deletion.PROTECT, related_name='payroll_rule', to='designations.designation')),
                ('updated_by', models.ForeignKey(blank=True, db_column='updated_by', db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'pay_designation_rules',
                'ordering': ['designation__department', 'designation__name'],
            },
        ),
        migrations.CreateModel(
            name='PayrollRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updated_at')),
                ('deleted_at', models.DateTimeField(blank=True, db_column='deleted_at', null=True)),
                ('is_active', models.BooleanField(db_column='is_active', default=True)),
                ('th_urid', models.CharField(db_column='th_urid', default=accounts.models.generate_custom_th_urid, editable=False, max_length=36, unique=True)),
                ('designation_snapshot', models.CharField(db_column='designation_snapshot', help_text='Designation name at time of run (immutable record)', max_length=200)),
                ('total_working_days', models.PositiveSmallIntegerField(db_column='total_working_days', default=0)),
                ('days_present', models.DecimalField(db_column='days_present', decimal_places=1, default=0, help_text='Effective days present (half-days contribute 0.5)', max_digits=4)),
                ('days_absent', models.DecimalField(db_column='days_absent', decimal_places=1, default=0, max_digits=4)),
                ('monthly_honorarium', models.DecimalField(db_column='monthly_honorarium', decimal_places=2, help_text='Honorarium snapshot at time of payroll run', max_digits=12)),
                ('gross_pay', models.DecimalField(db_column='gross_pay', decimal_places=2, default=0, help_text='Pro-rated gross pay based on attendance in future, but monthly_honorarium copy for now', max_digits=12)),
                ('tds_amount', models.DecimalField(db_column='tds_amount', decimal_places=2, default=0, max_digits=10)),
                ('epf_amount', models.DecimalField(db_column='epf_amount', decimal_places=2, default=0, max_digits=10)),
                ('esic_amount', models.DecimalField(db_column='esic_amount', decimal_places=2, default=0, max_digits=10)),
                ('other_deductions', models.DecimalField(db_column='other_deductions', decimal_places=2, default=0, help_text='Miscellaneous / one-off deductions', max_digits=10)),
                ('total_deductions', models.DecimalField(db_column='total_deductions', decimal_places=2, default=0, max_digits=10)),
                ('net_pay', models.DecimalField(db_column='net_pay', decimal_places=2, default=0, max_digits=12)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('COMPUTED', 'Computed'), ('APPROVED', 'Approved')], db_column='status', default='PENDING', max_length=20)),
                ('remarks', models.TextField(blank=True, db_column='remarks', null=True)),
                ('attendance_record', models.ForeignKey(blank=True, db_column='attendance_record_id', help_text='Source attendance record; null if entered manually', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payroll_records', to='attendance.attendancerecord')),
                ('created_by', models.ForeignKey(blank=True, db_column='created_by', db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, db_column='deleted_by', db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(db_column='employee_id', on_delete=django.db.models.deletion.PROTECT, related_name='payroll_records', to='employees.employeeprofile')),
                ('payroll_run', models.ForeignKey(db_column='payroll_run_id', on_delete=django.db.models.deletion.CASCADE, related_name='records', to='payroll.payrollrun')),
                ('updated_by', models.ForeignKey(blank=True, db_column='updated_by', db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'pay_payroll_records',
                'ordering': ['payroll_run', 'employee__user__employee_code'],
                'unique_together': {('payroll_run', 'employee')},
            },
        ),
    ]
