# Generated by Django 4.2.26 on 2026-06-26 05:47

import accounts.models
import departments.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('departments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updated_at')),
                ('deleted_at', models.DateTimeField(blank=True, db_column='deleted_at', null=True)),
                ('th_urid', models.CharField(db_column='th_urid', default=accounts.models.generate_custom_th_urid, editable=False, max_length=36, unique=True)),
                ('title', models.CharField(db_column='title', help_text='Short heading for the news.', max_length=250)),
                ('news_file', models.FileField(blank=True, help_text='Optional PDF attachment.', null=True, upload_to='news/', validators=[departments.models.validate_pdf])),
                ('is_active', models.BooleanField(db_column='is_active', default=True, help_text='Show this news on website.')),
                ('is_pinned', models.BooleanField(db_column='is_pinned', default=False, help_text='Pinned news appears before normal news.')),
                ('publish_date', models.DateTimeField(auto_now_add=True, db_column='publish_date')),
                ('expiry_date', models.DateTimeField(blank=True, db_column='expiry_date', help_text='News will stop displaying after this date.', null=True)),
                ('created_by', models.ForeignKey(blank=True, db_column='created_by', db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, db_column='deleted_by', db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, db_column='updated_by', db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'News',
                'verbose_name_plural': 'News',
                'db_table': 'newsboard',
                'ordering': ['-is_pinned', '-publish_date'],
                'indexes': [models.Index(fields=['is_active'], name='newsboard_is_acti_a28600_idx'), models.Index(fields=['publish_date'], name='newsboard_publish_454107_idx'), models.Index(fields=['expiry_date'], name='newsboard_expiry__f54ac6_idx')],
            },
        ),
    ]
