# Generated by Django 4.2.26 on 2026-06-10 12:02

import accounts.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('departments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updated_at')),
                ('deleted_at', models.DateTimeField(blank=True, db_column='deleted_at', null=True)),
                ('is_active', models.BooleanField(db_column='is_active', default=True)),
                ('th_urid', models.CharField(db_column='th_urid', default=accounts.models.generate_custom_th_urid, editable=False, max_length=36, unique=True)),
                ('att_month', models.PositiveSmallIntegerField(db_column='att_month', help_text='Attendance month (1 – 12)')),
                ('att_year', models.PositiveIntegerField(db_column='att_year')),
                ('status', models.CharField(choices=[('UPLOADED', 'Uploaded'), ('VERIFIED', 'Verified'), ('REJECTED', 'Rejected')], db_column='status', default='UPLOADED', max_length=20)),
                ('source_file', models.FileField(blank=True, db_column='source_file', help_text='Original spreadsheet uploaded by the manager (optional)', null=True, upload_to='attendance/source_files/')),
                ('verified_at', models.DateTimeField(blank=True, db_column='verified_at', null=True)),
                ('remarks', models.TextField(blank=True, db_column='remarks', null=True)),
                ('created_by', models.ForeignKey(blank=True, db_column='created_by', db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, db_column='deleted_by', db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(db_column='department_id', on_delete=django.db.models.deletion.PROTECT, related_name='attendance_uploads', to='departments.department')),
                ('updated_by', models.ForeignKey(blank=True, db_column='updated_by', db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('uploaded_by', models.ForeignKey(db_column='uploaded_by', on_delete=django.db.models.deletion.PROTECT, related_name='submitted_attendance_uploads', to=settings.AUTH_USER_MODEL)),
                ('verified_by', models.ForeignKey(blank=True, db_column='verified_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_attendance_uploads', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'att_uploads',
                'ordering': ['-att_year', '-att_month', 'department'],
                'unique_together': {('department', 'att_month', 'att_year')},
            },
        ),
        migrations.CreateModel(
            name='AttendanceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updated_at')),
                ('deleted_at', models.DateTimeField(blank=True, db_column='deleted_at', null=True)),
                ('is_active', models.BooleanField(db_column='is_active', default=True)),
                ('th_urid', models.CharField(db_column='th_urid', default=accounts.models.generate_custom_th_urid, editable=False, max_length=36, unique=True)),
                ('total_working_days', models.PositiveSmallIntegerField(db_column='total_working_days', default=0, help_text='Total scheduled working days in this month (set by the manager)')),
                ('days_present', models.PositiveSmallIntegerField(db_column='days_present', default=0, help_text='Full days present in office')),
                ('paid_leave', models.PositiveSmallIntegerField(db_column='paid_leave', default=0, help_text='Approved paid-leave days (treated as present for salary calculation)')),
                ('casual_leave', models.PositiveSmallIntegerField(db_column='casual_leave', default=0, help_text='Number of casual leave days')),
                ('sick_leave', models.PositiveSmallIntegerField(db_column='sick_leave', default=0, help_text='Number of sick leave days')),
                ('days_absent', models.PositiveSmallIntegerField(db_column='days_absent', default=0, help_text='Unauthorised / unmarked absences')),
                ('remarks', models.TextField(blank=True, db_column='remarks', null=True)),
                ('created_by', models.ForeignKey(blank=True, db_column='created_by', db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, db_column='deleted_by', db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(db_column='employee_id', on_delete=django.db.models.deletion.PROTECT, related_name='attendance_records', to='employees.employeeprofile')),
                ('updated_by', models.ForeignKey(blank=True, db_column='updated_by', db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('upload', models.ForeignKey(db_column='upload_id', on_delete=django.db.models.deletion.CASCADE, related_name='records', to='attendance.attendanceupload')),
            ],
            options={
                'db_table': 'att_records',
                'ordering': ['upload', 'employee__user__employee_code'],
                'unique_together': {('upload', 'employee')},
            },
        ),
    ]
