# Generated by Django 4.2.26 on 2026-06-17 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_leaveapplication_dailyattendance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaveapplication',
            name='leave_type',
            field=models.CharField(choices=[('MATERNITY', 'Maternity Leave (ML)'), ('CASUAL', 'Casual Leave (CL)'), ('SICK', 'Sick Leave (SL)')], max_length=10),
        ),
    ]
