# Generated by Django 4.2.26 on 2026-06-26 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0003_alter_leaveapplication_leave_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyattendance',
            name='holiday_reason',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
