# Generated by Django 4.2.26 on 2026-06-26 12:08

import accounts.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('attendance', '0004_dailyattendance_holiday_reason'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaveapplication',
            name='leave_type',
            field=models.CharField(choices=[('MATERNITY', 'Maternity Leave (ML)'), ('CASUAL', 'Casual Leave (CL)'), ('SICK', 'Sick Leave (SL)'), ('EARNED', 'Earned Leave (EL)'), ('LWP', 'Leave Without Pay (LWP)'), ('ESL', 'Extraordinary Sick Leave (ESL)')], max_length=10),
        ),
        migrations.CreateModel(
            name='LeaveLimits',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updated_at')),
                ('deleted_at', models.DateTimeField(blank=True, db_column='deleted_at', null=True)),
                ('is_active', models.BooleanField(db_column='is_active', default=True)),
                ('th_urid', models.CharField(db_column='th_urid', default=accounts.models.generate_custom_th_urid, editable=False, max_length=36, unique=True)),
                ('leave_type', models.CharField(choices=[('MATERNITY', 'Maternity Leave (ML)'), ('CASUAL', 'Casual Leave (CL)'), ('SICK', 'Sick Leave (SL)'), ('EARNED', 'Earned Leave (EL)'), ('LWP', 'Leave Without Pay (LWP)'), ('ESL', 'Extraordinary Sick Leave (ESL)')], max_length=10)),
                ('leave_count', models.PositiveSmallIntegerField(default=0)),
                ('created_by', models.ForeignKey(blank=True, db_column='created_by', db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, db_column='deleted_by', db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, db_column='updated_by', db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'att_leave_limit',
                'ordering': ['-leave_count'],
            },
        ),
    ]
