# Generated by Django 4.2.26 on 2026-07-30 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0005_alter_leaveapplication_leave_type_leavelimits'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyattendance',
            name='status',
            field=models.CharField(choices=[('PRESENT', 'Present'), ('ABSENT', 'Absent'), ('WEEKEND', 'Weekend (Saturday/Sunday)'), ('HOLIDAY', 'Public Holiday'), ('MATERNITY', 'Maternity Leave (ML)'), ('CASUAL', 'Casual Leave (CL)'), ('SICK', 'Sick Leave (SL)'), ('EARNED', 'Earned Leave (EL)'), ('LWP', 'Leave Without Pay (LWP)'), ('ESL', 'Extraordinary Sick Leave (ESL)')], default='PRESENT', max_length=15),
        ),
    ]
