# Generated by Django 4.2.26 on 2026-06-10 12:02

import accounts.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('employees', '0001_initial'),
        ('payroll', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalarySlip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updated_at')),
                ('deleted_at', models.DateTimeField(blank=True, db_column='deleted_at', null=True)),
                ('is_active', models.BooleanField(db_column='is_active', default=True)),
                ('th_urid', models.CharField(db_column='th_urid', default=accounts.models.generate_custom_th_urid, editable=False, max_length=36, unique=True)),
                ('slip_month', models.PositiveSmallIntegerField(db_column='slip_month', help_text='Salary month (1 – 12)')),
                ('slip_year', models.PositiveIntegerField(db_column='slip_year')),
                ('slip_number', models.CharField(db_column='slip_number', help_text='Auto-generated unique reference — SLIP/<year>/<mm>/<emp_code>', max_length=60, unique=True)),
                ('employee_code_snapshot', models.CharField(db_column='employee_code_snapshot', max_length=50)),
                ('employee_name_snapshot', models.CharField(db_column='employee_name_snapshot', max_length=200)),
                ('designation_snapshot', models.CharField(db_column='designation_snapshot', max_length=200)),
                ('department_snapshot', models.CharField(db_column='department_snapshot', max_length=200)),
                ('bank_name_snapshot', models.CharField(blank=True, db_column='bank_name_snapshot', max_length=200, null=True)),
                ('bank_account_snapshot', models.CharField(blank=True, db_column='bank_account_snapshot', max_length=50, null=True)),
                ('bank_ifsc_snapshot', models.CharField(blank=True, db_column='bank_ifsc_snapshot', max_length=20, null=True)),
                ('pan_snapshot', models.CharField(blank=True, db_column='pan_snapshot', help_text='PAN at time of generation (required for TDS slips)', max_length=20, null=True)),
                ('uan_snapshot', models.CharField(blank=True, db_column='uan_snapshot', help_text='UAN at time of generation (required for EPF slips)', max_length=20, null=True)),
                ('total_working_days', models.PositiveSmallIntegerField(db_column='total_working_days', default=0)),
                ('days_present', models.DecimalField(db_column='days_present', decimal_places=1, default=0, help_text='Effective payable days (half-days counted as 0.5)', max_digits=4)),
                ('days_absent', models.DecimalField(db_column='days_absent', decimal_places=1, default=0, max_digits=4)),
                ('monthly_honorarium', models.DecimalField(db_column='monthly_honorarium', decimal_places=2, help_text='Full monthly honorarium before pro-ration', max_digits=12)),
                ('gross_pay', models.DecimalField(db_column='gross_pay', decimal_places=2, help_text='Pro-rated gross = honorarium × (days_present / total_working_days)', max_digits=12)),
                ('tds_rate', models.DecimalField(db_column='tds_rate', decimal_places=2, default=0, help_text='TDS rate applied (% snapshot from SalaryStructure)', max_digits=5)),
                ('tds_amount', models.DecimalField(db_column='tds_amount', decimal_places=2, default=0, max_digits=10)),
                ('epf_rate', models.DecimalField(db_column='epf_rate', decimal_places=2, default=0, help_text='EPF rate applied (% snapshot)', max_digits=5)),
                ('epf_amount', models.DecimalField(db_column='epf_amount', decimal_places=2, default=0, max_digits=10)),
                ('esic_rate', models.DecimalField(db_column='esic_rate', decimal_places=2, default=0, help_text='ESIC rate applied (% snapshot)', max_digits=5)),
                ('esic_amount', models.DecimalField(db_column='esic_amount', decimal_places=2, default=0, max_digits=10)),
                ('other_deductions', models.DecimalField(db_column='other_deductions', decimal_places=2, default=0, max_digits=10)),
                ('total_deductions', models.DecimalField(db_column='total_deductions', decimal_places=2, default=0, max_digits=10)),
                ('net_pay', models.DecimalField(db_column='net_pay', decimal_places=2, max_digits=12)),
                ('net_pay_in_words', models.CharField(blank=True, db_column='net_pay_in_words', help_text="e.g. 'Rupees Forty-Two Thousand Only'", max_length=500, null=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('GENERATED', 'Generated'), ('DISPATCHED', 'Dispatched')], db_column='status', default='DRAFT', max_length=20)),
                ('generated_at', models.DateTimeField(blank=True, db_column='generated_at', null=True)),
                ('pdf_file', models.FileField(blank=True, db_column='pdf_file', help_text='Rendered PDF; populated after generation', null=True, upload_to='salary_slips/pdfs/')),
                ('remarks', models.TextField(blank=True, db_column='remarks', null=True)),
                ('created_by', models.ForeignKey(blank=True, db_column='created_by', db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, db_column='deleted_by', db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(db_column='employee_id', on_delete=django.db.models.deletion.PROTECT, related_name='salary_slips', to='employees.employeeprofile')),
                ('generated_by', models.ForeignKey(blank=True, db_column='generated_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_salary_slips', to=settings.AUTH_USER_MODEL)),
                ('payroll_record', models.OneToOneField(db_column='payroll_record_id', on_delete=django.db.models.deletion.PROTECT, related_name='salary_slip', to='payroll.payrollrecord')),
                ('updated_by', models.ForeignKey(blank=True, db_column='updated_by', db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'slip_salary_slips',
                'ordering': ['-slip_year', '-slip_month', 'employee__user__employee_code'],
                'unique_together': {('employee', 'slip_month', 'slip_year')},
            },
        ),
    ]
